### PR TITLE
Remove yarn.lock file

### PR DESCRIPTION
**Pull request by stefandoorn**
No need to have a lock file in there imo. Can only lead to outdated dependencies being installed (e.g. now jQuery < 3.0).

### CODE REVIEW

**Comment by lchrusciel** [comment]
build restarted

**Comment by pamil** [comment]
It makes builds reproducible though (we use the same practice for both Sylius application and single packages).

**Comment by stefandoorn** [comment]
Makes sense, but in the plugin skeleton itself composer.lock is ignored. Should we introduce and update both?

**Comment by pamil** [comment]
I've synced `yarn.lock` with the one from Sylius in #81, that should work fine (if done every time the original changes).

**Comment by pamil** [comment]
Rebased in #85.

**Pull request closed without merging**
