### PR TITLE
Upgrade to Chromedriver 2.35 to get around Network.DeleteCookie error

### PR DESCRIPTION
**Pull request by stefandoorn**
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1950

### CODE REVIEW

**Comment by stefandoorn** [comment]
I guess Chromedriver is in cache and therefore still using old version. @pjedrzejewski @pamil @lchrusciel Someone can clear the cache and run this again?

**Comment by lchrusciel** [comment]
@stefandoorn done

**Comment by stefandoorn** [comment]
Great. Seems to pass now :-)

**Comment by Zales0123** [comment]
Thank you Stefan!

**Pull request merged**
